export const foodEmojis = [
  // Fruits
  { name: "apple", emoji: "🍎" },
  { name: "green apple", emoji: "🍏" },
  { name: "banana", emoji: "🍌" },
  { name: "grapes", emoji: "🍇" },
  { name: "watermelon", emoji: "🍉" },
  { name: "tangerine", emoji: "🍊" },
  { name: "lemon", emoji: "🍋" },
  { name: "pineapple", emoji: "🍍" },
  { name: "mango", emoji: "🥭" },
  { name: "strawberry", emoji: "🍓" },
  { name: "blueberries", emoji: "🫐" },
  { name: "cherries", emoji: "🍒" },
  { name: "peach", emoji: "🍑" },
  { name: "pear", emoji: "🍐" },
  { name: "coconut", emoji: "🥥" },
  { name: "avocado", emoji: "🥑" },

  // Vegetables
  { name: "tomato", emoji: "🍅" },
  { name: "eggplant", emoji: "🍆" },
  { name: "potato", emoji: "🥔" },
  { name: "carrot", emoji: "🥕" },
  { name: "corn", emoji: "🌽" },
  { name: "hot pepper", emoji: "🌶️" },
  { name: "cucumber", emoji: "🥒" },
  { name: "leafy green", emoji: "🥬" },
  { name: "broccoli", emoji: "🥦" },
  { name: "garlic", emoji: "🧄" },
  { name: "onion", emoji: "🧅" },
  { name: "mushroom", emoji: "🍄" },
  { name: "peanuts", emoji: "🥜" },
  { name: "beans", emoji: "🫘" },
  { name: "ginger root", emoji: "🫚" },
  { name: "pod", emoji: "🫛" },

  // Breads, Grains & Dairy
  { name: "bread", emoji: "🍞" },
  { name: "baguette bread", emoji: "🥖" },
  { name: "flatbread", emoji: "🫓" },
  { name: "cheese", emoji: "🧀" },
  { name: "egg", emoji: "🥚" },
  { name: "milk", emoji: "🥛" },
  { name: "butter", emoji: "🧈" },
  { name: "salt", emoji: "🧂" },
  { name: "rice", emoji: "🍚" },
  { name: "cooked rice", emoji: "🍛" },
  { name: "rice cracker", emoji: "🍘" },

  // Protein & Main Dishes
  { name: "cut of meat", emoji: "🥩" },
  { name: "poultry leg", emoji: "🍗" },
  { name: "meat on bone", emoji: "🍖" },
  { name: "bacon", emoji: "🥓" },
  { name: "hamburger", emoji: "🍔" },
  { name: "french fries", emoji: "🍟" },
  { name: "pizza", emoji: "🍕" },
  { name: "hotdog", emoji: "🌭" },
  { name: "sandwich", emoji: "🥪" },
  { name: "taco", emoji: "🌮" },
  { name: "burrito", emoji: "🌯" },
  { name: "stuffed flatbread", emoji: "🥙" },
  { name: "falafel", emoji: "🧆" },
  { name: "shallow pan of food (paella)", emoji: "🥘" },
  { name: "stew", emoji: "🍲" },
  { name: "spaghetti", emoji: "🍝" },
  { name: "ramen", emoji: "🍜" },
  { name: "pot of food", emoji: "🍲" },
  { name: "bowl with spoon", emoji: "🥣" },
  { name: "fondue", emoji: "🫕" },
  { name: "canned food", emoji: "🥫" },
  { name: "sushi", emoji: "🍣" },
  { name: "bento box", emoji: "🍱" },
  { name: "fish cake with swirl", emoji: "🍥" },
  { name: "oden", emoji: "🍢" },
  { name: "dumpling", emoji: "🥟" },
  { name: "fortune cookie", emoji: "🥠" },
  { name: "moon cake", emoji: "🥮" },
  { name: "tamale", emoji: "🫔" },

  // Desserts & Sweets
  { name: "ice cream", emoji: "🍨" },
  { name: "shaved ice", emoji: "🍧" },
  { name: "soft ice cream", emoji: "🍦" },
  { name: "cake slice", emoji: "🍰" },
  { name: "birthday cake", emoji: "🎂" },
  { name: "shortcake", emoji: "🍰" },
  { name: "pie", emoji: "🥧" },
  { name: "cookie", emoji: "🍪" },
  { name: "chocolate bar", emoji: "🍫" },
  { name: "candy", emoji: "🍬" },
  { name: "lollipop", emoji: "🍭" },
  { name: "custard", emoji: "🍮" },
  { name: "honey pot", emoji: "🍯" },

  // Beverages
  { name: "glass of milk", emoji: "🥛" },
  { name: "coffee", emoji: "☕" },
  { name: "teacup without handle", emoji: "🍵" },
  { name: "bubble tea", emoji: "🧋" },
  { name: "mate drink", emoji: "🧉" },
  { name: "sake", emoji: "🍶" },
  { name: "beer mug", emoji: "🍺" },
  { name: "clinking beer mugs", emoji: "🍻" },
  { name: "wine glass", emoji: "🍷" },
  { name: "cocktail glass", emoji: "🍸" },
  { name: "tropical drink", emoji: "🍹" },
  { name: "champagne glass", emoji: "🥂" },
  { name: "bottle with popping cork", emoji: "🍾" },
  { name: "baby bottle", emoji: "🍼" },

  // Tableware & Others
  { name: "fork and knife", emoji: "🍴" },
  { name: "fork and knife with plate", emoji: "🍽️" },
  { name: "spoon", emoji: "🥄" },
  { name: "chopsticks", emoji: "🥢" },
  { name: "takeout box", emoji: "🥡" },
  { name: "basket", emoji: "🧺" },
];
